/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rayrobdod_util_Win7Taskbar */

#ifndef _Included_com_rayrobdod_util_Win7Taskbar
#define _Included_com_rayrobdod_util_Win7Taskbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rayrobdod_util_Win7Taskbar
 * Method:    setCurrentProcessAppID
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rayrobdod_util_Win7Taskbar_setCurrentProcessAppID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rayrobdod_util_Win7Taskbar
 * Method:    setRelaunchCommand
 * Signature: (Ljava/awt/Frame;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rayrobdod_util_Win7Taskbar_setRelaunchCommand
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
